baseURL = "https://til.12bit.vn/"
languageCode = "vi-vn"
title = "TIL"
theme = "hemingway"
enableGitInfo = true
disqusShortname = "shortname"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[params]
  description = "Little things learned everyday"
  author = "12bit.vn"

[params.highlight]
    style = "github"
    languages = ["go", "dockerfile"]

[[params.social]]
    url = "https://github.com/tanksuzuki"
    fa_icon = "fa-github"

[[params.social]]
    url = "https://twitter.com/tanksuzuki"
    fa_icon = "fa-twitter"

[[params.social]]
    url = "/index.xml"
    fa_icon = "fa-rss"