baseURL = "https://til.12bit.vn/"
languageCode = "vi-vn"
title = "TIL"
theme = "hemingway"
enableGitInfo = true
disqusShortname = "shortname"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[params]
  description = "Little things learned everyday"
  author = "12bit.vn"

[[params.social]]
    url = "https://github.com/12bitvn"
    fa_icon = "fa-github"

[[params.social]]
    url = "https://12bit.vn"
    fa_icon = "fa-globe"

[taxonomies]
  category = "categories"
  tag = "tags"